/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

/**
 *
 * @author jfria
 */
public class FrmMainLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMainLogin.class.getName());

    /**
     * Creates new form MainLogin
     */
    public FrmMainLogin() {
        initComponents();
        mostrarPanel(new PnlLogin());
    }
     public void mostrarPanel(javax.swing.JPanel panelNuevo) {
        //ajusta el panel entrante a la dimensiones del contenedor
       
        panelNuevo.setSize(pnlContenedor.getWidth(), pnlContenedor.getHeight());
        panelNuevo.setLocation(0, 0);
       //limpia el contenedor y agrega la nueva vista
        pnlContenedor.removeAll();
        pnlContenedor.add(panelNuevo, java.awt.BorderLayout.CENTER);
        //refresca la interfaz grafica para que los cambios sean visible 
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundMainLogin = new javax.swing.JPanel();
        lblCooperativa = new javax.swing.JPanel();
        lblcoop = new javax.swing.JLabel();
        lblManosALaObra = new javax.swing.JLabel();
        lblIconoCooperativa = new javax.swing.JLabel();
        lblSistemaDeCooperativa = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundMainLogin.setBackground(new java.awt.Color(24, 75, 95));
        backgroundMainLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCooperativa.setBackground(new java.awt.Color(221, 238, 249));

        lblcoop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblcoop.setForeground(new java.awt.Color(0, 0, 0));
        lblcoop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcoop.setText("Cooperativa");

        lblManosALaObra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblManosALaObra.setForeground(new java.awt.Color(0, 0, 0));
        lblManosALaObra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManosALaObra.setText("Manos a la Obra");

        lblIconoCooperativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trabajo-en-equipo256.png"))); // NOI18N

        javax.swing.GroupLayout lblCooperativaLayout = new javax.swing.GroupLayout(lblCooperativa);
        lblCooperativa.setLayout(lblCooperativaLayout);
        lblCooperativaLayout.setHorizontalGroup(
            lblCooperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCooperativaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(lblCooperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcoop, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManosALaObra))
                .addGap(111, 111, 111))
            .addGroup(lblCooperativaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblIconoCooperativa, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        lblCooperativaLayout.setVerticalGroup(
            lblCooperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCooperativaLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(lblIconoCooperativa, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblcoop, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManosALaObra)
                .addGap(80, 80, 80))
        );

        backgroundMainLogin.add(lblCooperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 610));

        lblSistemaDeCooperativa.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblSistemaDeCooperativa.setForeground(new java.awt.Color(0, 0, 0));
        lblSistemaDeCooperativa.setText("Sistema de cooperativa");
        backgroundMainLogin.add(lblSistemaDeCooperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        backgroundMainLogin.add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 650, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundMainLogin;
    private javax.swing.JPanel lblCooperativa;
    private javax.swing.JLabel lblIconoCooperativa;
    private javax.swing.JLabel lblManosALaObra;
    private javax.swing.JLabel lblSistemaDeCooperativa;
    private javax.swing.JLabel lblcoop;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
