/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

/**
 *
 * @author jfria
 */
public class PnlLogin extends javax.swing.JPanel {

    /**
     * Creates new form PnlLogin
     */
    public PnlLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroundLogin = new javax.swing.JPanel();
        lblInicioDeSesion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContrasenia = new javax.swing.JLabel();
        pwdContrasenia = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        pnlBotonIngresar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlBotonRegistar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackgroundLogin.setBackground(new java.awt.Color(244, 239, 230));

        lblInicioDeSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInicioDeSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblInicioDeSesion.setText("Inicio de Sesion");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Cedula");

        txtNombre.setBackground(new java.awt.Color(244, 239, 230));
        txtNombre.setText("Digite su Cedula sin guiones");
        txtNombre.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenia.setText("Contraseña:");

        pwdContrasenia.setBackground(new java.awt.Color(244, 239, 230));
        pwdContrasenia.setText("jPasswordField2");
        pwdContrasenia.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        pnlBotonIngresar.setBackground(new java.awt.Color(24, 75, 95));
        pnlBotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlBotonIngresarLayout = new javax.swing.GroupLayout(pnlBotonIngresar);
        pnlBotonIngresar.setLayout(pnlBotonIngresarLayout);
        pnlBotonIngresarLayout.setHorizontalGroup(
            pnlBotonIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonIngresarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlBotonIngresarLayout.setVerticalGroup(
            pnlBotonIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotonRegistar.setBackground(new java.awt.Color(24, 75, 95));
        pnlBotonRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonRegistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBotonRegistarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlBotonRegistarMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrar");

        javax.swing.GroupLayout pnlBotonRegistarLayout = new javax.swing.GroupLayout(pnlBotonRegistar);
        pnlBotonRegistar.setLayout(pnlBotonRegistarLayout);
        pnlBotonRegistarLayout.setHorizontalGroup(
            pnlBotonRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonRegistarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlBotonRegistarLayout.setVerticalGroup(
            pnlBotonRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonRegistarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBackgroundLoginLayout = new javax.swing.GroupLayout(pnlBackgroundLogin);
        pnlBackgroundLogin.setLayout(pnlBackgroundLoginLayout);
        pnlBackgroundLoginLayout.setHorizontalGroup(
            pnlBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLoginLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(pnlBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInicioDeSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtNombre)
                    .addComponent(jSeparator1)
                    .addGroup(pnlBackgroundLoginLayout.createSequentialGroup()
                        .addComponent(pnlBotonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBotonRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(pwdContrasenia))
                .addGap(0, 196, Short.MAX_VALUE))
        );
        pnlBackgroundLoginLayout.setVerticalGroup(
            pnlBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLoginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblInicioDeSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pnlBackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBotonRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        add(pnlBackgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBotonRegistarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonRegistarMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnlBotonRegistarMouseReleased

    private void pnlBotonRegistarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonRegistarMousePressed
        // TODO add your handling code here:
        FrmMainLogin ventanaPadre = (FrmMainLogin) javax.swing.SwingUtilities.getWindowAncestor(this);
        ventanaPadre.mostrarPanel(new PnlRegistro());
        
    }//GEN-LAST:event_pnlBotonRegistarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblInicioDeSesion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlBackgroundLogin;
    private javax.swing.JPanel pnlBotonIngresar;
    private javax.swing.JPanel pnlBotonRegistar;
    private javax.swing.JPasswordField pwdContrasenia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
