/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inf514.sistemacooperativa.vista;

import com.inf514.sistemacooperativa.dao.UsuarioDAO;
import com.inf514.sistemacooperativa.modelo.Usuario;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jfria
 */
public class PnlRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PnlRegistro
     */
    public PnlRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroundRegistro = new javax.swing.JPanel();
        lblRegistroNuevoUsuario = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        pwContrasenia = new javax.swing.JPasswordField();
        lblRepetirContrasenia = new javax.swing.JLabel();
        pwRepitaContrasenia = new javax.swing.JPasswordField();
        pnlRegistarBotton = new javax.swing.JPanel();
        txtRegistar = new javax.swing.JLabel();
        pnlBotonAtras = new javax.swing.JPanel();
        txtRegistar1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackgroundRegistro.setBackground(new java.awt.Color(244, 239, 230));

        lblRegistroNuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistroNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRegistroNuevoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistroNuevoUsuario.setText("Registro Nuevo usuario");

        lblNombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCompleto.setText("Nombre Completo");

        txtNombreCompleto.setText("Nombre Completo");

        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("Cedula");

        txtCedula.setText("digite su cedula sin guiones");
        txtCedula.addActionListener(this::txtCedulaActionPerformed);

        lblFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento.setText("Fecha de nacimiento");

        txtFechaNacimiento.setText("fecha de nacimiento");
        txtFechaNacimiento.addActionListener(this::txtFechaNacimientoActionPerformed);

        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("Telefono:");

        txtTelefono.setText("Telefono");
        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);

        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo Electronico:");

        txtCorreoElectronico.setText("Corro Electronico");

        lblContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenia.setText("Contrasenia:");

        pwContrasenia.setText("jPasswordField1");

        lblRepetirContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        lblRepetirContrasenia.setText("Repita Su Contrasenia");

        pwRepitaContrasenia.setText("jPasswordField1");

        pnlRegistarBotton.setBackground(new java.awt.Color(24, 75, 95));
        pnlRegistarBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlRegistarBottonMousePressed(evt);
            }
        });
        pnlRegistarBotton.addPropertyChangeListener(this::pnlRegistarBottonPropertyChange);

        txtRegistar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegistar.setForeground(new java.awt.Color(0, 0, 0));
        txtRegistar.setText("REGISTAR");

        javax.swing.GroupLayout pnlRegistarBottonLayout = new javax.swing.GroupLayout(pnlRegistarBotton);
        pnlRegistarBotton.setLayout(pnlRegistarBottonLayout);
        pnlRegistarBottonLayout.setHorizontalGroup(
            pnlRegistarBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistarBottonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlRegistarBottonLayout.setVerticalGroup(
            pnlRegistarBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistarBottonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtRegistar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlBotonAtras.setBackground(new java.awt.Color(24, 75, 95));
        pnlBotonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBotonAtrasMousePressed(evt);
            }
        });

        txtRegistar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegistar1.setForeground(new java.awt.Color(0, 0, 0));
        txtRegistar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistar1.setText("Atras");

        javax.swing.GroupLayout pnlBotonAtrasLayout = new javax.swing.GroupLayout(pnlBotonAtras);
        pnlBotonAtras.setLayout(pnlBotonAtrasLayout);
        pnlBotonAtrasLayout.setHorizontalGroup(
            pnlBotonAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonAtrasLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(txtRegistar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlBotonAtrasLayout.setVerticalGroup(
            pnlBotonAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonAtrasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtRegistar1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundRegistroLayout = new javax.swing.GroupLayout(pnlBackgroundRegistro);
        pnlBackgroundRegistro.setLayout(pnlBackgroundRegistroLayout);
        pnlBackgroundRegistroLayout.setHorizontalGroup(
            pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pnlRegistarBotton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pnlBotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblRegistroNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRepetirContrasenia)
                                    .addComponent(pwRepitaContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombreCompleto)
                                .addComponent(lblTelefono)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtFechaNacimiento)
                                .addComponent(txtNombreCompleto)))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addComponent(lblFechaNacimiento)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlBackgroundRegistroLayout.setVerticalGroup(
            pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCompleto)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(lblCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimiento)
                    .addComponent(lblRepetirContrasenia))
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwRepitaContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundRegistroLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(pnlBackgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRegistarBotton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBotonAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        add(pnlBackgroundRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void pnlBotonAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonAtrasMousePressed
        // TODO add your handling code here:
        FrmMainLogin ventanaPadre = (FrmMainLogin) javax.swing.SwingUtilities.getWindowAncestor(this);
        ventanaPadre.mostrarPanel(new PnlLogin());
    }//GEN-LAST:event_pnlBotonAtrasMousePressed

    private void pnlRegistarBottonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pnlRegistarBottonPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlRegistarBottonPropertyChange

    private void pnlRegistarBottonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegistarBottonMousePressed
        // TODO add your handling code here:
        String cedula = txtCedula.getText();
        String nombre = txtNombreCompleto.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreoElectronico.getText();
        
        String contrasenia = new String(pwContrasenia.getPassword());
        
        try{
            Usuario nuevoUsuario = new Usuario(cedula,nombre,telefono,correo,contrasenia);
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarioDAO.guardarUsuario(nuevoUsuario);
           
            JOptionPane.showMessageDialog(this, "Usuario Registrado con exito!. ");
            FrmMainLogin ventanaPadre = (FrmMainLogin) SwingUtilities.getWindowAncestor(this);
            ventanaPadre.mostrarPanel(new PnlLogin());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_pnlRegistarBottonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblRegistroNuevoUsuario;
    private javax.swing.JLabel lblRepetirContrasenia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlBackgroundRegistro;
    private javax.swing.JPanel pnlBotonAtras;
    private javax.swing.JPanel pnlRegistarBotton;
    private javax.swing.JPasswordField pwContrasenia;
    private javax.swing.JPasswordField pwRepitaContrasenia;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JLabel txtRegistar;
    private javax.swing.JLabel txtRegistar1;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
